### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [uapasha/js-kottans-hw#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить

`````` html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```
``````

**Comment by uapasha** [comment]
[Homework1](https://github.com/uapasha/js-kottans-hw/blob/master/hw1/markup.html)

**Comment by mkozhukharenko** [comment]
don't use aside as a wrapper
https://github.com/uapasha/js-kottans-hw/blob/master/hw1/markup.html#L10
https://github.com/uapasha/js-kottans-hw/blob/master/hw1/markup.html#L49

https://github.com/vrd/kottans-js-2016/issues/2#issuecomment-221067829:

>  Aside is not a sidebar or wrapper for random stuff - it's container for secondary(secondary to main article or website)!

**Comment by mkozhukharenko** [comment]
why do you put section https://github.com/uapasha/js-kottans-hw/blob/master/hw1/markup.html#L11 inside a header? rethink you solution, read this: [header](http://html5doctor.com/the-header-element/)

**Comment by mkozhukharenko** [comment]
this shouldn't be inside a nav https://github.com/uapasha/js-kottans-hw/blob/master/hw1/markup.html#L41-L46 
[read more about a nav](http://html5doctor.com/nav-element/)

**Comment by mkozhukharenko** [comment]
extend this element to have an image and a figcaption https://github.com/uapasha/js-kottans-hw/blob/master/hw1/markup.html#L50

**Comment by mkozhukharenko** [comment]
https://github.com/uapasha/js-kottans-hw/blob/master/hw1/markup.html#L72-L74
https://github.com/uapasha/js-kottans-hw/blob/master/hw1/markup.html#L100
if it look like a small it does not mean that it's a  `small` element
[read more](http://html5doctor.com/small-hr-element/)

**Comment by mkozhukharenko** [comment]
article inside an article? mm 
https://github.com/uapasha/js-kottans-hw/blob/master/hw1/markup.html#L133-L135

**Comment by uapasha** [comment]
Thanks a lot for the review!
Made some changes:
https://github.com/uapasha/js-kottans-hw/commit/651b3110f1b082b6cfaf4ca73ec4ddd94d07e9f8

**Comment by mkozhukharenko** [comment]
``` html
            <header>
                <h2>Комментарии (42)</h2>
            </header>
```

you don't need a `header` if it has only one heading

``` html
                <header>
                    avatar, user, date
                </header>
```

I'd make:

``` html
                <h1>
                    avatar, user, date
                </h1>
```

**Comment by mkozhukharenko** [comment]
@uapasha you forgot about this https://github.com/uapasha/js-kottans-hw/issues/2#issuecomment-221079133
If you have different opinion - just express it, please 😸

**Comment by uapasha** [comment]
@mkozhukharenko No, I changed markup according to your advice.[#2](https://github.com/uapasha/js-kottans-hw/issues/2#issuecomment-221079133) Thanks!

**Comment by mkozhukharenko** [comment]
you a welcome. 
good job! 👍
